// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjawxptfxvufusajwmph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqYXd4cHRmeHZ1ZnVzYWp3bXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNzg4NjgsImV4cCI6MjA1NzY1NDg2OH0.I7yfnMmOGo-7q-Jf8gqIPg90mRiT-S47Egll3ZzHEak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);